# Stub configuration for Divy A2A agent server
# Fill in all fields, then run `divy_a2a convert`

# === Agent and Framework Import ===
agent_export_name: "intern_agent"
agent_file_name: "agent"
framework: "openai"

# === AgentCard metadata ===
name: "My Agent"
description: "A brief description of what your agent does."
url: "http://localhost:10003"
version: "1.0.0"
host: "localhost"
port: "10003"

defaultInputModes:
  - "text/plain"
defaultOutputModes:
  - "text/plain"

capabilities:
  streaming: False
  pushNotifications: True

skills:
  - id: "reddit_search"
    name: "Search Reddit and parse posts"
    description: "Fetches Reddit posts, parses them, writes to file, returns summary"
    tags:
      - "reddit"
      - "internship"
      - "parsing"
    examples:
      - "Topic: Google SRE internship…"